### PR TITLE
#7 Feature: Crud operation for routes

### PR DESCRIPTION
**Pull request by Niyonkuru1**
## What does this PR do?
Create, read, update and delete routes
## Description of Task to be completed?
As an operator, I want to create routes so that buses can travel in pre-defined routes.

- The operator should be able to create, delete, and update a route.
- The operator should be able to view a paginated list of routes in the system.
- Appropriate error messages are displayed on unsuccessful attempts
- The users should be able to view a route's details.

## How should this be manually tested?
`Clone the repo`
`checkout` to branch `ft-crud-operation-routes-7`
pull the changes by `git pull`
install all packages by running `npm install`
start app by `running npm run start:dev`
In your API testing tool (**postman** is recommended for that) call API

- Method: GET http://localhost:5000/api/v1/route/ to `view/read` all registered routes.
- Method: GET http://localhost:5000/api/v1/route/{id} to `view/read` one specific registered route
- Method: POST http://localhost:5000/api/v1/route/ to `create/register` new route
- Method: PUT http://localhost:5000/api/v1/route/{id} to `update` one specific  route
- Method: DELETE http://localhost:5000/api/v1/route/{id} to `delete` one specific route

### To test language:
- Under *Headers* in **postman** hopefully, insert the property called `Accept-Language` and set it to the either `en` or `kiny` or `fr` according to which language you want; then make a **request**

## Any background context you want to provide?
Note that you should send the request with *origin* and *destination*  for **creating** new route or **updating** it in the
request body

- Format : 
` {
   "origin":"Mulindi",
   "destination":"Kimironko",
"description":"hello there nice to meet you again!"
 }`
## What are the relevant pivotal tracker stories?
[Trello Board](https://trello.com/c/fkcTK4dw/7-crud-operations-for-routes)

Screenshots (if appropriate)
N/A

Questions:
N/A

### CODE REVIEW

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
LGTM though you have to first remove the conflicts.

**Comment by Sylvain222** [comment]
Conflict resolved successfully

**Comment by Sylvain222** [comment]
> LGTM though you have to first remove the conflicts.

Resolved successfully

**Review by thepatrickniyo — APPROVED** [review]

**Review by tysepa — APPROVED** [review]

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
You need to resolve the conflicts and please add translations

**Comment by Niyonkuru1** [comment]
> You need to resolve the conflicts and please add translations

Yes, I am going to resolve the conflict, 
but about translation I am missing the way to do it since I am interacting with database and I have no way to insert those data in the json files of translation

**Comment by Niyonkuru1** [comment]
> You need to resolve the conflicts and please add translations

Translation done successfully, thank you

**Review by thepatrickniyo — APPROVED** [review]

**Pull request merged**
