### PR TITLE
#16 Feature: Enquire real time bus's info

### PR DESCRIPTION
**Pull request by Salim-54**
### What does this PR do?
- Enquire buses' info
### Description of Task to be completed?

As a user, I should be able to retrieve details of a bus so that I can plan my next move accordingly.

- The user should be able to view the location of a bus in real-time.
- The user should be able to view the status of the bus (moving, at rest, stuck in traffic)
- The user should be able to view the total number of commuters on the bus.
- The user should be able to view the bus type
- The user should be able to view available seats
- Appropriate error messages are displayed on unsuccessful attempts.

### How should this be manually tested?
`Clone the repo`

`checkout` to branch `ft-enquire-bus-info-16`

pull the changes by `git pull`

install all packages by `running npm install`

start app by running `npm run start:dev`

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[[Trello Board](https://trello.com/c/6mUnQf3N/16-enquire-buses-info)]
### Screen shots
N/A

### CODE REVIEW

**Comment by Salim-54** [comment]
[Enquire buses' info](https://trello.com/c/6mUnQf3N/16-enquire-buses-info)

**Comment by Salim-54** [comment]
[Enquire buses' info](https://trello.com/c/6mUnQf3N/16-enquire-buses-info)

**Comment by Salim-54** [comment]
[Enquire buses' info](https://trello.com/c/6mUnQf3N/16-enquire-buses-info)

**Review by tysepa — APPROVED** [review]

**Review by tysepa — COMMENTED** [review]
try to solve the conflicts and push others to finish your task

**Review by Niyonkuru1 — APPROVED** [review]

**Pull request closed without merging**
