### PR TITLE
#10 Feature: Register drivers & operators

### PR DESCRIPTION
**Pull request by Salim-54**
### What does this PR do?
- Register drivers & operators
### Description of Task to be completed?

**As an administrator**, I want to be able to register the drivers and operators into the system, so that they can be able to log in the system. 

**As an administrator**, I want to provide the email of the driver/operator, so that they receive an email with a login, randomly generated password.

- The administrator should be able to register a new driver or a new operator.
- An email containing a random password should be sent to the provided email.
- The driver or operator should be able to sign in to the app using their email and the provided password.
- Appropriate error messages are displayed on unsuccessful attempts
-
### How should this be manually tested?
`Clone the repo`

`checkout` to branch `ft-register-operators-n-drivers-10`

pull the changes by `git pull`

install all packages by `running npm install`

start app by running `npm run start:dev`

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[[Trello Board](https://trello.com/c/gpFRNRl8/10-register-drivers-operators)]
### Screen shots
Screenshot (323)

### CODE REVIEW

**Comment by Salim-54** [comment]
[Register drivers & operators](https://trello.com/c/gpFRNRl8/10-register-drivers-operators)

**Review by tysepa — APPROVED** [review]
Be on update to solve the conflicts

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
Remove the conflicts in `api.json`

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks good to me

**Review by thepatrickniyo — APPROVED** [review]

**Pull request merged**
